# render.yaml - El plano de construcci칩n para nuestra aplicaci칩n

databases:
  - name: vrsalud-db         # Nombre del servicio de la base de datos
    databaseName: vrsalud_db # Nombre de la base de datos interna
    user: vrsalud_user       # Nombre del usuario de la base de datos

services:
  - type: web
    name: vrsalud-backend    # Nombre de nuestro servicio web
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vrsalud-db # Debe coincidir con el nombre de la base de datos de arriba
          property: internalConnectionString
      - key: SECRET_KEY
        generateValue: true # Render generar치 una clave secreta segura autom치ticamente
      - key: WEB_CONCURRENCY
        value: 4